// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cperrin88/gotya/artifact/http (interfaces: Client)
//
// Generated by this command:
//
//	mockgen -destination=mocks/http.go . Client
//

// Artifact mock_http is a generated GoMock package.
package mock_http

import (
	context "context"
	url "net/url"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DownloadIndex mocks base method.
func (m *MockClient) DownloadIndex(ctx context.Context, repoURL *url.URL, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadIndex", ctx, repoURL, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadIndex indicates an expected call of DownloadIndex.
func (mr *MockClientMockRecorder) DownloadIndex(ctx, repoURL, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadIndex", reflect.TypeOf((*MockClient)(nil).DownloadIndex), ctx, repoURL, filePath)
}

// DownloadArtifact mocks base method.
func (m *MockClient) DownloadArtifact(ctx context.Context, packageURL *url.URL, filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadArtifact", ctx, packageURL, filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadArtifact indicates an expected call of DownloadArtifact.
func (mr *MockClientMockRecorder) DownloadArtifact(ctx, packageURL, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadArtifact", reflect.TypeOf((*MockClient)(nil).DownloadArtifact), ctx, packageURL, filePath)
}
