version: "2"
run:
  tests: true
linters:
  default: standard
  enable:
    - gosec
    - gocritic
    - revive
    - gocyclo
    - funlen
    - ineffassign
    - misspell
    - goconst
    - unused
    - dupl
    - decorder
    - staticcheck
    - err113
    - testifylint
    - nilnil
    - copyloopvar
    - funcorder
  settings:
    funlen:
      lines: -1
      statements: 50
    decorder:
      disable-dec-order-check: false
    gocritic:
      enabled-checks:
        - importShadow
        - builtinShadow
        - builtinShadowDecl
    gosec:
      excludes:
        - G301  # Expect directory permissions to be 0750 or less
        - G302  # Expect file permissions to be 0600 or less
        - G304  # Potential file inclusion via variable
        - G306  # Expect WriteFile permissions to be 0600 or less
        - G115  # integer overflow conversion int -> uint32
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - funlen
          - goconst
          - err113