// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cperrin88/gotya/artifact/index (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/index.go . Manager
//

// Artifact mock_index is a generated GoMock package.
package mock_index

import (
	context "context"
	reflect "reflect"
	time "time"

	index "github.com/cperrin88/gotya/pkg/index"
	repository "github.com/cperrin88/gotya/pkg/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// FindArtifacts mocks base method.
func (m *MockManager) FindArtifacts(name string) (map[string][]*index.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindArtifacts", name)
	ret0, _ := ret[0].(map[string][]*index.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindArtifacts indicates an expected call of FindArtifacts.
func (mr *MockManagerMockRecorder) FindArtifacts(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindArtifacts", reflect.TypeOf((*MockManager)(nil).FindArtifacts), name)
}

// GetCacheAge mocks base method.
func (m *MockManager) GetCacheAge(name string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCacheAge", name)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCacheAge indicates an expected call of GetCacheAge.
func (mr *MockManagerMockRecorder) GetCacheAge(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCacheAge", reflect.TypeOf((*MockManager)(nil).GetCacheAge), name)
}

// GetIndex mocks base method.
func (m *MockManager) GetIndex(name string) (*index.Index, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndex", name)
	ret0, _ := ret[0].(*index.Index)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndex indicates an expected call of GetIndex.
func (mr *MockManagerMockRecorder) GetIndex(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndex", reflect.TypeOf((*MockManager)(nil).GetIndex), name)
}

// IsCacheStale mocks base method.
func (m *MockManager) IsCacheStale(name string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCacheStale", name)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCacheStale indicates an expected call of IsCacheStale.
func (mr *MockManagerMockRecorder) IsCacheStale(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCacheStale", reflect.TypeOf((*MockManager)(nil).IsCacheStale), name)
}

// ListRepositories mocks base method.
func (m *MockManager) ListRepositories() []*repository.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRepositories")
	ret0, _ := ret[0].([]*repository.Repository)
	return ret0
}

// ListRepositories indicates an expected call of ListRepositories.
func (mr *MockManagerMockRecorder) ListRepositories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRepositories", reflect.TypeOf((*MockManager)(nil).ListRepositories))
}

// ResolveArtifact mocks base method.
func (m *MockManager) ResolveArtifact(name, version, os, arch string) (*index.Artifact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveArtifact", name, version, os, arch)
	ret0, _ := ret[0].(*index.Artifact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveArtifact indicates an expected call of ResolveArtifact.
func (mr *MockManagerMockRecorder) ResolveArtifact(name, version, os, arch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveArtifact", reflect.TypeOf((*MockManager)(nil).ResolveArtifact), name, version, os, arch)
}

// Sync mocks base method.
func (m *MockManager) Sync(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockManagerMockRecorder) Sync(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockManager)(nil).Sync), ctx, name)
}

// SyncAll mocks base method.
func (m *MockManager) SyncAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncAll indicates an expected call of SyncAll.
func (mr *MockManagerMockRecorder) SyncAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncAll", reflect.TypeOf((*MockManager)(nil).SyncAll), ctx)
}
