// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cperrin88/gotya/pkg/orchestrator (interfaces: ArtifactResolver,ArtifactManager,Downloader)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/orchestrator.go . ArtifactResolver,ArtifactManager,Downloader
//

// Package mock_orchestrator is a generated GoMock package.
package mock_orchestrator

import (
	context "context"
	reflect "reflect"

	download "github.com/cperrin88/gotya/pkg/download"
	index "github.com/cperrin88/gotya/pkg/index"
	model "github.com/cperrin88/gotya/pkg/model"
	gomock "go.uber.org/mock/gomock"
)

// MockArtifactResolver is a mock of ArtifactResolver interface.
type MockArtifactResolver struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactResolverMockRecorder
	isgomock struct{}
}

// MockArtifactResolverMockRecorder is the mock recorder for MockArtifactResolver.
type MockArtifactResolverMockRecorder struct {
	mock *MockArtifactResolver
}

// NewMockArtifactResolver creates a new mock instance.
func NewMockArtifactResolver(ctrl *gomock.Controller) *MockArtifactResolver {
	mock := &MockArtifactResolver{ctrl: ctrl}
	mock.recorder = &MockArtifactResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactResolver) EXPECT() *MockArtifactResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockArtifactResolver) Resolve(ctx context.Context, req index.ResolveRequest) (index.ResolvedArtifacts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, req)
	ret0, _ := ret[0].(index.ResolvedArtifacts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockArtifactResolverMockRecorder) Resolve(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockArtifactResolver)(nil).Resolve), ctx, req)
}

// MockArtifactManager is a mock of ArtifactManager interface.
type MockArtifactManager struct {
	ctrl     *gomock.Controller
	recorder *MockArtifactManagerMockRecorder
	isgomock struct{}
}

// MockArtifactManagerMockRecorder is the mock recorder for MockArtifactManager.
type MockArtifactManagerMockRecorder struct {
	mock *MockArtifactManager
}

// NewMockArtifactManager creates a new mock instance.
func NewMockArtifactManager(ctrl *gomock.Controller) *MockArtifactManager {
	mock := &MockArtifactManager{ctrl: ctrl}
	mock.recorder = &MockArtifactManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArtifactManager) EXPECT() *MockArtifactManagerMockRecorder {
	return m.recorder
}

// InstallArtifact mocks base method.
func (m *MockArtifactManager) InstallArtifact(ctx context.Context, desc *model.IndexArtifactDescriptor, localPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallArtifact", ctx, desc, localPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallArtifact indicates an expected call of InstallArtifact.
func (mr *MockArtifactManagerMockRecorder) InstallArtifact(ctx, desc, localPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallArtifact", reflect.TypeOf((*MockArtifactManager)(nil).InstallArtifact), ctx, desc, localPath)
}

// MockDownloader is a mock of Downloader interface.
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
	isgomock struct{}
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader.
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance.
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return m.recorder
}

// FetchAll mocks base method.
func (m *MockDownloader) FetchAll(ctx context.Context, items []download.Item, opts download.Options) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAll", ctx, items, opts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAll indicates an expected call of FetchAll.
func (mr *MockDownloaderMockRecorder) FetchAll(ctx, items, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAll", reflect.TypeOf((*MockDownloader)(nil).FetchAll), ctx, items, opts)
}
